import express from "express";
import { authController } from "../controllers/authController.js";
import { requireAuth } from "../middleware/auth.js";
import { authRateLimiter, emailResendRateLimiter, passwordResetRateLimiter } from "../config/rateLimiter.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { privacyController } from "../controllers/privacyController.js";
import { requireCsrf } from "../services/sessionService.js";

const router = express.Router();
router.post("/signup", authRateLimiter, asyncHandler(authController.signup));
router.post("/login", authRateLimiter, asyncHandler(authController.login));
router.get("/csrf", asyncHandler(authController.csrf));
router.post("/refresh", authRateLimiter, requireCsrf, asyncHandler(authController.refresh));
router.post("/logout", requireCsrf, asyncHandler(authController.logout));
router.post("/logout-all", requireAuth, requireCsrf, asyncHandler(authController.logoutAll));
router.get("/me", requireAuth, asyncHandler(authController.me));
router.post("/verify-email", authRateLimiter, asyncHandler(authController.verifyEmail));
router.post("/resend-verification", requireAuth, emailResendRateLimiter, asyncHandler(authController.resendVerification));
router.post("/forgot-password", passwordResetRateLimiter, asyncHandler(authController.forgotPassword));
router.post("/reset-password", passwordResetRateLimiter, asyncHandler(authController.resetPassword));
router.patch("/preferences", requireAuth, asyncHandler(authController.updatePreferences));
router.post("/accept-policies", requireAuth, asyncHandler(authController.acceptPolicies));
router.get("/data-export", requireAuth, asyncHandler(privacyController.exportData));
router.patch("/privacy-settings", requireAuth, asyncHandler(privacyController.updateRetention));
router.delete("/account", requireAuth, asyncHandler(privacyController.deleteAccount));
router.get("/account-deletion-status", asyncHandler(privacyController.deletionStatus));
export default router;
